### ISSUE TITLE
broken repositories support

### ISSUE THREAD

**Issue by jefimm** [tsachev/lein-bom#1]
The following project breaks the plugin

> (defproject demo "0.0.1"
  :bom {:import [[io.netty/netty-bom "4.0.54.Final"]
                 [com.fasterxml.jackson/jackson-bom "2.9.3"]
                 [org.springframework.boot/spring-boot-dependencies "1.5.9.RELEASE"]]}
  :plugins [[lein-bom "0.2.0-SNAPSHOT"]]
  :repositories [["snapshots" {:url      "https://maven.company.fun/snapshots"
                               :username :env/company_maven_username
                               :password :env/company_maven_password}]
                 ["releases" {:url      "https://maven.company.fun/releases"
                              :username :env/company_maven_username
                              :password :env/company_maven_password}]]
  :managed-dependencies [[io.netty/netty-buffer "4.1.19.Final"]]
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [io.netty/netty-codec]
                 [com.fasterxml.jackson.core/jackson-core]])

Error:
`java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.lang.String
 at cemerick.pomegranate.aether$authentication.invokeStatic (aether.clj:173)
    cemerick.pomegranate.aether$authentication.invoke (aether.clj:173)
    cemerick.pomegranate.aether$set_authentication.invokeStatic (aether.clj:184)
    cemerick.pomegranate.aether$set_authentication.invoke (aether.clj:181)
    cemerick.pomegranate.aether$make_repository.invokeStatic (aether.clj:211)
    cemerick.pomegranate.aether$make_repository.invoke (aether.clj:200)
    clojure.lang.Var.invoke (Var.java:388)
    lein_bom.aether$read_artifact_descriptors_STAR_$fn__701.invoke (aether.clj:94)
    clojure.core$map$fn__5851.invoke (core.clj:2755)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.PersistentVector.create (PersistentVector.java:73)
    clojure.lang.LazilyPersistentVector.create (LazilyPersistentVector.java:44)
    clojure.core$vec.invokeStatic (core.clj:377)
    clojure.core$vec.invoke (core.clj:367)
    lein_bom.aether$read_artifact_descriptors_STAR_.invokeStatic (aether.clj:94)
    lein_bom.aether$read_artifact_descriptors_STAR_.doInvoke (aether.clj:74)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    lein_bom.aether$read_artifact_descriptors.invokeStatic (aether.clj:106)
    lein_bom.aether$read_artifact_descriptors.doInvoke (aether.clj:104)
    clojure.lang.RestFn.invoke (RestFn.java:619)
    leiningen.bom$resolve_imported_dependencies.invokeStatic (bom.clj:10)
    leiningen.bom$resolve_imported_dependencies.invoke (bom.clj:9)
    leiningen.bom$manage_dependencies.invokeStatic (bom.clj:71)
    leiningen.bom$manage_dependencies.invoke (bom.clj:68)
    lein_bom.plugin$middleware.invokeStatic (plugin.clj:8)
    lein_bom.plugin$middleware.invoke (plugin.clj:7)
    clojure.lang.Var.invoke (Var.java:384)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:817)
    leiningen.core.project$apply_middleware.invoke (project.clj:810)
    clojure.core.protocols$fn__8144.invokeStatic (protocols.clj:168)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__8099$G__8094__8108.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__8131.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__8073$G__8068__8086.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6828)
    clojure.core$reduce.invoke (core.clj:6810)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:812)
    leiningen.core.project$apply_middleware.invoke (project.clj:810)
    leiningen.core.project$activate_middleware.invokeStatic (project.clj:844)
    leiningen.core.project$activate_middleware.invoke (project.clj:840)
    leiningen.core.project$init_project.invokeStatic (project.clj:986)
    leiningen.core.project$init_project.invoke (project.clj:974)
    leiningen.core.project$read.invokeStatic (project.clj:1057)
    leiningen.core.project$read.invoke (project.clj:1054)
    leiningen.core.project$read.invokeStatic (project.clj:1058)
    leiningen.core.project$read.invoke (project.clj:1054)
    leiningen.core.main$_main$fn__6681.invoke (main.clj:447)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.main$main_opt.invokeStatic (main.clj:491)
    clojure.main$main_opt.invoke (main.clj:487)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)
`

**Comment by tsachev** [comment]
@jefimm thanks for the report

**Comment by gonzalopardogms** [comment]
What was the report fix? 

:) thank you
